#!/bin/bash

# Comprehensive RBAC Application Script
# This script documents all RBAC changes needed across all route files

echo "🔒 RBAC Comprehensive Application Report"
echo "=========================================="
echo ""

echo "✅ COMPLETED:"
echo "  - middleware/rbac.js created"
echo "  - routes/users.js - Full RBAC (User Management)"
echo "  - routes/departments.js - Fixed department & bed management"
echo "  - routes/patients.js - Partial RBAC (needs completion)"
echo ""

echo "⏳ REMAINING ROUTE FILES TO FIX:"
echo ""

echo "1. routes/opd.js - OPD Module"
echo "   Needs:"
echo "   - GET /tokens → requirePermission('OPD_ACCESS')"
echo "   - POST /tokens → requirePermission('OPD_ACCESS')"
echo "   - GET /queue → requirePermission('OPD_ACCESS')"
echo "   - POST /call-next → requirePermission('OPD_CONSULTATION')"
echo "   - POST /complete → requirePermission('OPD_CONSULTATION')"
echo ""

echo "2. routes/appointments.js - Appointments"
echo "   Needs:"
echo "   - GET / → requirePermission('OPD_ACCESS')"
echo "   - POST / → requirePermission('OPD_ACCESS')"
echo "   - GET /:id → requirePermission('OPD_ACCESS')"
echo "   - PATCH /:id → requirePermission('OPD_ACCESS')"
echo "   - DELETE /:id → requireAdmin()"
echo ""

echo "3. routes/ipd.js - IPD Module"
echo "   Needs:"
echo "   - GET /admissions → requirePermission('IPD_ACCESS')"
echo "   - POST /admissions → requirePermission('IPD_ACCESS')"
echo "   - GET /admissions/:id → requirePermission('IPD_ACCESS')"
echo "   - PATCH /admissions/:id → requirePermission('IPD_ACCESS')"
echo "   - POST /discharge → requirePermission('IPD_DISCHARGE')"
echo ""

echo "4. routes/pharmacy.js - Pharmacy Module"
echo "   Needs:"
echo "   - GET /medicines → requirePermission('PHARMACY_READ')"
echo "   - POST /medicines → requirePermission('PHARMACY_MANAGE')"
echo "   - GET /medicines/:id → requirePermission('PHARMACY_READ')"
echo "   - PATCH /medicines/:id → requirePermission('PHARMACY_MANAGE')"
echo "   - GET /prescriptions → requirePermission('PHARMACY_READ')"
echo "   - POST /prescriptions → requirePermission('PRESCRIPTION_CREATE')"
echo "   - GET /prescriptions/:id → requirePermission('PHARMACY_READ')"
echo "   - POST /orders → requirePermission('PHARMACY_MANAGE')"
echo ""

echo "5. routes/lab.js - Lab Module"
echo "   Needs:"
echo "   - GET /tests → requirePermission('LAB_ORDER')"
echo "   - POST /tests → requirePermission('LAB_ORDER')"
echo "   - GET /tests/:id → requirePermission('LAB_ORDER')"
echo "   - PATCH /tests/:id/sample → requirePermission('LAB_PROCESS')"
echo "   - PATCH /tests/:id/results → requirePermission('LAB_RESULTS')"
echo ""

echo "6. routes/radiology.js - Radiology Module"
echo "   Needs:"
echo "   - GET /tests → requirePermission('RADIOLOGY_ORDER')"
echo "   - POST /tests → requirePermission('RADIOLOGY_ORDER')"
echo "   - GET /tests/:id → requirePermission('RADIOLOGY_ORDER')"
echo "   - PATCH /tests/:id → requirePermission('RADIOLOGY_PROCESS')"
echo ""

echo "7. routes/billing.js - Billing Module"
echo "   Needs:"
echo "   - GET /invoices → requirePermission('BILLING_VIEW')"
echo "   - POST /invoices → requirePermission('BILLING_MANAGE')"
echo "   - GET /invoices/:id → requirePermission('BILLING_VIEW')"
echo "   - POST /payments → requirePermission('BILLING_MANAGE')"
echo "   - GET /statistics → requirePermission('BILLING_REPORTS')"
echo ""

echo "8. routes/organizations.js - Organization Management"
echo "   Needs:"
echo "   - GET / → requirePermission('ORG_VIEW')"
echo "   - POST / → requireSuperAdmin()"
echo "   - GET /:id → requirePermission('ORG_VIEW')"
echo "   - PATCH /:id → requireAdmin()"
echo "   - DELETE /:id → requireSuperAdmin()"
echo ""

echo "9. routes/patients.js - Patient Management (PARTIAL)"
echo "   Needs completion for all routes"
echo ""

echo ""
echo "📋 MANUAL FIX REQUIRED:"
echo "Each route file needs middleware added to route definitions"
echo "Pattern:"
echo "  router.get('/path', authenticateToken, requirePermission('GROUP'), async (req, res) => {"
echo ""
echo "See APPLY_RBAC_PLAN.md for detailed permissions matrix"
